export const heroes = [
    {
        id: 1,
        name: "npc_dota_hero_antimage",
        localized_name: "Anti-Mage",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Escape", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/antimage.png?",
        legs: 2,
        skill: "Mana Void"
    },
    {
        id: 2,
        name: "npc_dota_hero_axe",
        localized_name: "Axe",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Initiator", "Durable", "Disabler", "Jungler", "Carry"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/axe.png?",
        legs: 2,
        skill: "Battle Hunger"
    },
    {
        id: 3,
        name: "npc_dota_hero_bane",
        localized_name: "Bane",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Disabler", "Nuker", "Durable"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/bane.png?",
        legs: 4,
        skill: "Enfeeble"
    },
    {
        id: 4,
        name: "npc_dota_hero_bloodseeker",
        localized_name: "Bloodseeker",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Disabler", "Jungler", "Nuker", "Initiator"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/bloodseeker.png?",
        legs: 2,
        skill: "Thirst"
    },
    {
        id: 5,
        name: "npc_dota_hero_crystal_maiden",
        localized_name: "Crystal Maiden",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Disabler", "Nuker", "Jungler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/crystal_maiden.png?",
        legs: 2,
        skill: "Arcane Aura"
    },
    {
        id: 6,
        name: "npc_dota_hero_drow_ranger",
        localized_name: "Drow Ranger",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Disabler", "Pusher"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/drow_ranger.png?",
        legs: 2,
        skill: "Marksmanship"
    },
    {
        id: 7,
        name: "npc_dota_hero_earthshaker",
        localized_name: "Earthshaker",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Support", "Initiator", "Disabler", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/earthshaker.png?",
        legs: 2,
        skill: "Fissure",
    },
    {
        id: 8,
        name: "npc_dota_hero_juggernaut",
        localized_name: "Juggernaut",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Pusher", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/juggernaut.png?",
        legs: 2,
        skill: "Blade Dance",
    },
    {
        id: 9,
        name: "npc_dota_hero_mirana",
        localized_name: "Mirana",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Support", "Escape", "Nuker", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/mirana.png?",
        legs: 2,
        skill: "Starstorm",
    },
    {
        id: 10,
        name: "npc_dota_hero_morphling",
        localized_name: "Morphling",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Escape", "Durable", "Nuker", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/morphling.png?",
        legs: 0,
        skill: "Adaptive Strike",
    },
    {
        id: 11,
        name: "npc_dota_hero_nevermore",
        localized_name: "Shadow Fiend",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/nevermore.png?",
        legs: 0,
        skill: "Presence of the Dark Lord",
    },
    {
        id: 12,
        name: "npc_dota_hero_phantom_lancer",
        localized_name: "Phantom Lancer",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Escape", "Pusher", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/phantom_lancer.png?",
        legs: 2,
        skill: "Juxtapose",
    },
    {
        id: 13,
        name: "npc_dota_hero_puck",
        localized_name: "Puck",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Initiator", "Disabler", "Escape", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/puck.png?",
        legs: 2,
        skill: "Waning Rift",
    },
    {
        id: 14,
        name: "npc_dota_hero_pudge",
        localized_name: "Pudge",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Disabler", "Initiator", "Durable", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/pudge.png?",
        legs: 2,
        skill: "Dismember",
    },
    {
        id: 15,
        name: "npc_dota_hero_razor",
        localized_name: "Razor",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Durable", "Nuker", "Pusher"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/razor.png?",
        legs: 0,
        skill: "Storm Surge",
    },
    {
        id: 16,
        name: "npc_dota_hero_sand_king",
        localized_name: "Sand King",
        primary_attr: "str",
        attack_type: "Melee",
        roles: [
            "Initiator",
            "Disabler",
            "Support",
            "Nuker",
            "Escape",
            "Jungler",
        ],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/sand_king.png?",
        legs: 6,
        skill: "Caustic Finale",
    },
    {
        id: 17,
        name: "npc_dota_hero_storm_spirit",
        localized_name: "Storm Spirit",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Carry", "Escape", "Nuker", "Initiator", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/storm_spirit.png?",
        legs: 2,
        skill: "Overload",
    },
    {
        id: 18,
        name: "npc_dota_hero_sven",
        localized_name: "Sven",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Disabler", "Initiator", "Durable", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/sven.png?",
        legs: 2,
        skill: "Storm Hammer",
    },
    {
        id: 19,
        name: "npc_dota_hero_tiny",
        localized_name: "Tiny",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Nuker", "Pusher", "Initiator", "Durable", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/tiny.png?",
        legs: 2,
        skill: "Avalanche",
    },
    {
        id: 20,
        name: "npc_dota_hero_vengefulspirit",
        localized_name: "Vengeful Spirit",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Support", "Initiator", "Disabler", "Nuker", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/vengefulspirit.png?",
        legs: 2,
        skill: "Wave of Terror",
    },
    {
        id: 21,
        name: "npc_dota_hero_windrunner",
        localized_name: "Windranger",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Carry", "Support", "Disabler", "Escape", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/windrunner.png?",
        legs: 2,
        skill: "Poweshot",
    },
    {
        id: 22,
        name: "npc_dota_hero_zuus",
        localized_name: "Zeus",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Nuker", "Carry"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/zuus.png?",
        legs: 2,
        skill: "Arc Lightning",
    },
    {
        id: 23,
        name: "npc_dota_hero_kunkka",
        localized_name: "Kunkka",
        primary_attr: "str",
        attack_type: "Melee",
        roles: [
            "Carry",
            "Support",
            "Disabler",
            "Initiator",
            "Durable",
            "Nuker",
        ],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/kunkka.png?",
        legs: 2,
        skill: "Tidebringer",
    },
    {
        id: 25,
        name: "npc_dota_hero_lina",
        localized_name: "Lina",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Carry", "Nuker", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/lina.png?",
        legs: 2,
        skill: "Light Strike Array",
    },
    {
        id: 26,
        name: "npc_dota_hero_lion",
        localized_name: "Lion",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Disabler", "Nuker", "Initiator"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/lion.png?",
        legs: 2,
        skill: "Earth Spike",
    },
    {
        id: 27,
        name: "npc_dota_hero_shadow_shaman",
        localized_name: "Shadow Shaman",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Pusher", "Disabler", "Nuker", "Initiator"],
        legs: 2,
        skill: "Ether Shock",
    },
    {
        id: 28,
        name: "npc_dota_hero_slardar",
        localized_name: "Slardar",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Durable", "Initiator", "Disabler", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/slardar.png?",
        legs: 0,
        skill: "Guardian Sprint",
    },
    {
        id: 29,
        name: "npc_dota_hero_tidehunter",
        localized_name: "Tidehunter",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Initiator", "Durable", "Disabler", "Nuker", "Carry"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/tidehunter.png?",
        legs: 2,
        skill: "Ravage",
    },
    {
        id: 30,
        name: "npc_dota_hero_witch_doctor",
        localized_name: "Witch Doctor",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Nuker", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/witch_doctor.png?",
        legs: 2,
        skill: "Death Ward",
    },
    {
        id: 31,
        name: "npc_dota_hero_lich",
        localized_name: "Lich",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/lich.png?",
        legs: 2,
        skill: "Frost Blast",
    },
    {
        id: 32,
        name: "npc_dota_hero_riki",
        localized_name: "Riki",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Escape", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/riki.png?",
        legs: 2,
        skill: "Tricks of the trade",
    },
    {
        id: 33,
        name: "npc_dota_hero_enigma",
        localized_name: "Enigma",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Disabler", "Jungler", "Initiator", "Pusher"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/enigma.png?",
        legs: 0,
        skill: "Malefice",
    },
    {
        id: 34,
        name: "npc_dota_hero_tinker",
        localized_name: "Tinker",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Carry", "Nuker", "Pusher"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/tinker.png?",
        legs: 2,
        skill: "Keen Conveyance",
    },
    {
        id: 35,
        name: "npc_dota_hero_sniper",
        localized_name: "Sniper",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/sniper.png?",
        legs: 2,
        skill: "Assassinate",
    },
    {
        id: 36,
        name: "npc_dota_hero_necrolyte",
        localized_name: "Necrophos",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Carry", "Nuker", "Durable", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/necrolyte.png?",
        legs: 2,
        skill: "Death Pulse",
    },
    {
        id: 37,
        name: "npc_dota_hero_warlock",
        localized_name: "Warlock",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Initiator", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/warlock.png?",
        legs: 2,
        skill: "Upheaval",
    },
    {
        id: 38,
        name: "npc_dota_hero_beastmaster",
        localized_name: "Beastmaster",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Initiator", "Disabler", "Durable", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/beastmaster.png?",
        legs: 2,
        skill: "Inner Beast",
    },
    {
        id: 39,
        name: "npc_dota_hero_queenofpain",
        localized_name: "Queen of Pain",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Carry", "Nuker", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/queenofpain.png?",
        legs: 2,
        skill: "Shadow Strike",
    },
    {
        id: 40,
        name: "npc_dota_hero_venomancer",
        localized_name: "Venomancer",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Support", "Nuker", "Initiator", "Pusher", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/venomancer.png?",
        legs: 0,
        skill: "Poison Sting",
    },
    {
        id: 41,
        name: "npc_dota_hero_faceless_void",
        localized_name: "Faceless Void",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Initiator", "Disabler", "Escape", "Durable"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/faceless_void.png?",
        legs: 2,
        skill: "Time Dilation",
    },
    {
        id: 42,
        name: "npc_dota_hero_skeleton_king",
        localized_name: "Wraith King",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Support", "Durable", "Disabler", "Initiator"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/skeleton_king.png?",
        legs: 2,
        skill: "Mortal Strike",
    },
    {
        id: 43,
        name: "npc_dota_hero_death_prophet",
        localized_name: "Death Prophet",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Carry", "Pusher", "Nuker", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/death_prophet.png?",
        legs: 2,
        skill: "Silence",
    },
    {
        id: 44,
        name: "npc_dota_hero_phantom_assassin",
        localized_name: "Phantom Assassin",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/phantom_assassin.png?",
        legs: 2,
        skill: "Phantom Strike",
    },
    {
        id: 45,
        name: "npc_dota_hero_pugna",
        localized_name: "Pugna",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Nuker", "Pusher"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/pugna.png?",
        legs: 2,
        skill: "Decrepify",
    },
    {
        id: 46,
        name: "npc_dota_hero_templar_assassin",
        localized_name: "Templar Assassin",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/templar_assassin.png?",
        legs: 2,
        skill: "Refraction",
    },
    {
        id: 47,
        name: "npc_dota_hero_viper",
        localized_name: "Viper",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Durable", "Initiator", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/viper.png?",
        legs: 0,
        skill: "Poison Attack",
    },
    {
        id: 48,
        name: "npc_dota_hero_luna",
        localized_name: "Luna",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Nuker", "Pusher"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/luna.png?",
        legs: 2,
        skill: "Lunar Blessing",
    },
    {
        id: 49,
        name: "npc_dota_hero_dragon_knight",
        localized_name: "Dragon Knight",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Pusher", "Durable", "Disabler", "Initiator", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/dragon_knight.png?",
        legs: 2,
        skill: "Breathe Fire",
    },
    {
        id: 50,
        name: "npc_dota_hero_dazzle",
        localized_name: "Dazzle",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Nuker", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/dazzle.png?",
        legs: 2,
        skill: "Poison Touch",
    },
    {
        id: 51,
        name: "npc_dota_hero_rattletrap",
        localized_name: "Clockwerk",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Initiator", "Disabler", "Durable", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/rattletrap.png?",
        legs: 2,
        skill: "Battery Assault",
    },
    {
        id: 52,
        name: "npc_dota_hero_leshrac",
        localized_name: "Leshrac",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Carry", "Support", "Nuker", "Pusher", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/leshrac.png?",
        legs: 4,
        skill: "Lightning Storm",
    },
    {
        id: 53,
        name: "npc_dota_hero_furion",
        localized_name: "Nature's Prophet",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Carry", "Jungler", "Pusher", "Escape", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/furion.png?",
        skill: "Teleportation",
        legs: 2,
    },
    {
        id: 54,
        name: "npc_dota_hero_life_stealer",
        localized_name: "Lifestealer",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Durable", "Jungler", "Escape", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/life_stealer.png?",
        skill: "Rage",
        legs: 2,
    },
    {
        id: 55,
        name: "npc_dota_hero_dark_seer",
        localized_name: "Dark Seer",
        primary_attr: "int",
        attack_type: "Melee",
        roles: ["Initiator", "Jungler", "Escape", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/dark_seer.png?",
        skill: "Surge",
        legs: 2,
    },
    {
        id: 56,
        name: "npc_dota_hero_clinkz",
        localized_name: "Clinkz",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Escape", "Pusher"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/clinkz.png?",
        skill: "Death Pact",
        legs: 2,
    },
    {
        id: 57,
        name: "npc_dota_hero_omniknight",
        localized_name: "Omniknight",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Support", "Durable", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/omniknight.png?",
        skill: "Hammer of Purity",
        legs: 2,
    },
    {
        id: 58,
        name: "npc_dota_hero_enchantress",
        localized_name: "Enchantress",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Jungler", "Pusher", "Durable", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/enchantress.png?",
        skill: "Nature's Attendants",
        legs: 4,
    },
    {
        id: 59,
        name: "npc_dota_hero_huskar",
        localized_name: "Huskar",
        primary_attr: "str",
        attack_type: "Ranged",
        roles: ["Carry", "Durable", "Initiator"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/huskar.png?",
        skill: "Inner Fire",
        legs: 2,
    },
    {
        id: 60,
        name: "npc_dota_hero_night_stalker",
        localized_name: "Night Stalker",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Initiator", "Durable", "Disabler", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/night_stalker.png?",
        skill: "Void",
        legs: 2,
    },
    {
        id: 61,
        name: "npc_dota_hero_broodmother",
        localized_name: "Broodmother",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Pusher", "Escape", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/broodmother.png?",
        skill: "Insatiable Hunger",
        legs: 8,
    },
    {
        id: 62,
        name: "npc_dota_hero_bounty_hunter",
        localized_name: "Bounty Hunter",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Escape", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/bounty_hunter.png?",
        skill: "Shadow Walk",
        legs: 2,
    },
    {
        id: 63,
        name: "npc_dota_hero_weaver",
        localized_name: "Weaver",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/weaver.png?",
        skill: "The Swarm",
        legs: 4,
    },
    {
        id: 64,
        name: "npc_dota_hero_jakiro",
        localized_name: "Jakiro",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Nuker", "Pusher", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/jakiro.png?",
        skill: "Liquid Fire",
        legs: 2,
    },
    {
        id: 65,
        name: "npc_dota_hero_batrider",
        localized_name: "Batrider",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Initiator", "Jungler", "Disabler", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/batrider.png?",
        skill: "Firefly",
        legs: 2,
    },
    {
        id: 66,
        name: "npc_dota_hero_chen",
        localized_name: "Chen",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Jungler", "Pusher"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/chen.png?",
        skill: "Penitence",
        legs: 2,
    },
    {
        id: 67,
        name: "npc_dota_hero_spectre",
        localized_name: "Spectre",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Durable", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/spectre.png?",
        skill: "Desolate",
        legs: 0,
    },
    {
        id: 68,
        name: "npc_dota_hero_ancient_apparition",
        localized_name: "Ancient Apparition",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Disabler", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/ancient_apparition.png?",
        skill: "Chilling Touch",
        legs: 0,
    },
    {
        id: 69,
        name: "npc_dota_hero_doom_bringer",
        localized_name: "Doom",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Disabler", "Initiator", "Durable", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/doom_bringer.png?",
        skill: "Infernal Blade",
        legs: 2,
    },
    {
        id: 70,
        name: "npc_dota_hero_ursa",
        localized_name: "Ursa",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Jungler", "Durable", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/ursa.png?",
        skill: "Earthshock",
        legs: 2,
    },
    {
        id: 71,
        name: "npc_dota_hero_spirit_breaker",
        localized_name: "Spirit Breaker",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Initiator", "Disabler", "Durable", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/spirit_breaker.png?",
        skill: "Bulldoze",
        legs: 2,
    },
    {
        id: 72,
        name: "npc_dota_hero_gyrocopter",
        localized_name: "Gyrocopter",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Nuker", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/gyrocopter.png?",
        skill: "Call Down",
        legs: 2,
    },
    {
        id: 73,
        name: "npc_dota_hero_alchemist",
        localized_name: "Alchemist",
        primary_attr: "str",
        attack_type: "Melee",
        roles: [
            "Carry",
            "Support",
            "Durable",
            "Disabler",
            "Initiator",
            "Nuker",
        ],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/alchemist.png?",
        skill: "Greevil's Greed",
        legs: 2,
    },
    {
        id: 74,
        name: "npc_dota_hero_invoker",
        localized_name: "Invoker",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Carry", "Nuker", "Disabler", "Escape", "Pusher"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/invoker.png?",
        skill: "Invoke",
        legs: 2,
    },
    {
        id: 75,
        name: "npc_dota_hero_silencer",
        localized_name: "Silencer",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Carry", "Support", "Disabler", "Initiator", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/silencer.png?",
        skill: "Arcane Curse",
        legs: 2,
    },
    {
        id: 76,
        name: "npc_dota_hero_obsidian_destroyer",
        localized_name: "Outworld Destroyer",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Carry", "Nuker", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/obsidian_destroyer.png?",
        skill: "Arcane Orb",
        legs: 4,
    },
    {
        id: 77,
        name: "npc_dota_hero_lycan",
        localized_name: "Lycan",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Pusher", "Jungler", "Durable", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/lycan.png?",
        skill: "Shapeshift",
        legs: 2,
    },
    {
        id: 78,
        name: "npc_dota_hero_brewmaster",
        localized_name: "Brewmaster",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Initiator", "Durable", "Disabler", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/brewmaster.png?",
        skill: "Thunder Clap",
        legs: 2,
    },
    {
        id: 79,
        name: "npc_dota_hero_shadow_demon",
        localized_name: "Shadow Demon",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Disabler", "Initiator", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/shadow_demon.png?",
        skill: "Disruption",
        legs: 2,
    },
    {
        id: 80,
        name: "npc_dota_hero_lone_druid",
        localized_name: "Lone Druid",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Pusher", "Jungler", "Durable"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/lone_druid.png?",
        skill: "Spirit Link",
        legs: 2,
    },
    {
        id: 81,
        name: "npc_dota_hero_chaos_knight",
        localized_name: "Chaos Knight",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Disabler", "Durable", "Pusher", "Initiator"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/chaos_knight.png?",
        skill: "Phantasm",
        legs: 2,
    },
    {
        id: 82,
        name: "npc_dota_hero_meepo",
        localized_name: "Meepo",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Escape", "Nuker", "Disabler", "Initiator", "Pusher"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/meepo.png?",
        skill: "Earthbind",
        legs: 2,
    },
    {
        id: 83,
        name: "npc_dota_hero_treant",
        localized_name: "Treant Protector",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Support", "Initiator", "Durable", "Disabler", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/treant.png?",
        skill: "Nature's Grasp",
        legs: 2,
    },
    {
        id: 84,
        name: "npc_dota_hero_ogre_magi",
        localized_name: "Ogre Magi",
        primary_attr: "int",
        attack_type: "Melee",
        roles: ["Support", "Nuker", "Disabler", "Durable", "Initiator"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/ogre_magi.png?",
        skill: "Ignite",
        legs: 2,
    },
    {
        id: 85,
        name: "npc_dota_hero_undying",
        localized_name: "Undying",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Support", "Durable", "Disabler", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/undying.png?",
        skill: "Decay",
        legs: 2,
    },
    {
        id: 86,
        name: "npc_dota_hero_rubick",
        localized_name: "Rubick",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Disabler", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/rubick.png?",
        skill: "Arcane Supremacy",
        legs: 2,
    },
    {
        id: 87,
        name: "npc_dota_hero_disruptor",
        localized_name: "Disruptor",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Disabler", "Nuker", "Initiator"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/disruptor.png?",
        skill: "Thunder Strike",
        legs: 2,
    },
    {
        id: 88,
        name: "npc_dota_hero_nyx_assassin",
        localized_name: "Nyx Assassin",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Disabler", "Nuker", "Initiator", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/nyx_assassin.png?",
        skill: "Impale",
        legs: 6,
    },
    {
        id: 89,
        name: "npc_dota_hero_naga_siren",
        localized_name: "Naga Siren",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: [
            "Carry",
            "Support",
            "Pusher",
            "Disabler",
            "Initiator",
            "Escape",
        ],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/naga_siren.png?",
        skill: "Mirror Image",
        legs: 0,
    },
    {
        id: 90,
        name: "npc_dota_hero_keeper_of_the_light",
        localized_name: "Keeper of the Light",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Nuker", "Disabler", "Jungler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/keeper_of_the_light.png?",
        skill: "Spirit Form",
        legs: 2,
    },
    {
        id: 91,
        name: "npc_dota_hero_wisp",
        localized_name: "Io",
        primary_attr: "str",
        attack_type: "Ranged",
        roles: ["Support", "Escape", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/wisp.png?",
        skill: "Overcharge",
        legs: 0,
    },
    {
        id: 92,
        name: "npc_dota_hero_visage",
        localized_name: "Visage",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Nuker", "Durable", "Disabler", "Pusher"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/visage.png?",
        skill: "Grave Chill",
        legs: 2,
    },
    {
        id: 93,
        name: "npc_dota_hero_slark",
        localized_name: "Slark",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Escape", "Disabler", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/slark.png?",
        skill: "Dark Pact",
        legs: 2,
    },
    {
        id: 94,
        name: "npc_dota_hero_medusa",
        localized_name: "Medusa",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Disabler", "Durable"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/medusa.png?",
        skill: "Split Shot",
        legs: 0,
    },
    {
        id: 95,
        name: "npc_dota_hero_troll_warlord",
        localized_name: "Troll Warlord",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Pusher", "Disabler", "Durable"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/troll_warlord.png?",
        skill: "Berserker's Rage",
        legs: 2,
    },
    {
        id: 96,
        name: "npc_dota_hero_centaur",
        localized_name: "Centaur Warrunner",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Durable", "Initiator", "Disabler", "Nuker", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/centaur.png?",
        skill: "Retaliate",
        legs: 4,
    },
    {
        id: 97,
        name: "npc_dota_hero_magnataur",
        localized_name: "Magnus",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Initiator", "Disabler", "Nuker", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/magnataur.png?",
        skill: "Shockwave",
        legs: 4,
    },
    {
        id: 98,
        name: "npc_dota_hero_shredder",
        localized_name: "Timbersaw",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Nuker", "Durable", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/shredder.png?",
        skill: "Whirling Death",
        legs: 2,
    },
    {
        id: 99,
        name: "npc_dota_hero_bristleback",
        localized_name: "Bristleback",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Durable", "Initiator", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/bristleback.png?",
        skill: "Warpath",
        legs: 2,
    },
    {
        id: 100,
        name: "npc_dota_hero_tusk",
        localized_name: "Tusk",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Initiator", "Disabler", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/tusk.png?",
        skill: "Tag Team",
        legs: 2,
    },
    {
        id: 101,
        name: "npc_dota_hero_skywrath_mage",
        localized_name: "Skywrath Mage",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Nuker", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/skywrath_mage.png?",
        skill: "Arcane Bolt",
        legs: 2,
    },
    {
        id: 102,
        name: "npc_dota_hero_abaddon",
        localized_name: "Abaddon",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Support", "Carry", "Durable"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/abaddon.png?",
        skill: "Mist Coil",
        legs: 2,
    },
    {
        id: 103,
        name: "npc_dota_hero_elder_titan",
        localized_name: "Elder Titan",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Initiator", "Disabler", "Nuker", "Durable"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/elder_titan.png?",
        skill: "Natural Order",
        legs: 2,
    },
    {
        id: 104,
        name: "npc_dota_hero_legion_commander",
        localized_name: "Legion Commander",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Disabler", "Initiator", "Durable", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/legion_commander.png?",
        skill: "Moment of Courage",
        legs: 2,
    },
    {
        id: 105,
        name: "npc_dota_hero_techies",
        localized_name: "Techies",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Nuker", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/techies.png?",
        skill: "Reactive Tazer",
        legs: 6,
    },
    {
        id: 106,
        name: "npc_dota_hero_ember_spirit",
        localized_name: "Ember Spirit",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Escape", "Nuker", "Disabler", "Initiator"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/ember_spirit.png?",
        skill: "Sleight of Fist",
        legs: 2,
    },
    {
        id: 107,
        name: "npc_dota_hero_earth_spirit",
        localized_name: "Earth Spirit",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Nuker", "Escape", "Disabler", "Initiator", "Durable"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/earth_spirit.png?",
        skill: "Boulder Smash",
        legs: 2,
    },
    {
        id: 108,
        name: "npc_dota_hero_abyssal_underlord",
        localized_name: "Underlord",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Support", "Nuker", "Disabler", "Durable", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/abyssal_underlord.png?",
        skill: "Firestorm",
        legs: 2,
    },
    {
        id: 109,
        name: "npc_dota_hero_terrorblade",
        localized_name: "Terrorblade",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Pusher", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/terrorblade.png?",
        skill: "Conjure Image",
        legs: 2,
    },
    {
        id: 110,
        name: "npc_dota_hero_phoenix",
        localized_name: "Phoenix",
        primary_attr: "str",
        attack_type: "Ranged",
        roles: ["Support", "Nuker", "Initiator", "Escape", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/phoenix.png?",
        skill: "Fire Spirits",
        legs: 2,
    },
    {
        id: 111,
        name: "npc_dota_hero_oracle",
        localized_name: "Oracle",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Nuker", "Disabler", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/oracle.png?",
        skill: "Purifying Flames",
        legs: 0,
    },
    {
        id: 112,
        name: "npc_dota_hero_winter_wyvern",
        localized_name: "Winter Wyvern",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Disabler", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/winter_wyvern.png?",
        skill: "Arctic Burn",
        legs: 2,
    },
    {
        id: 113,
        name: "npc_dota_hero_arc_warden",
        localized_name: "Arc Warden",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Carry", "Escape", "Nuker"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/arc_warden.png?",
        skill: "Flux",
        legs: 2,
    },
    {
        id: 114,
        name: "npc_dota_hero_monkey_king",
        localized_name: "Monkey King",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Escape", "Disabler", "Initiator"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/monkey_king.png?",
        skill: "Boundless Strike",
        legs: 2,
    },
    {
        id: 119,
        name: "npc_dota_hero_dark_willow",
        localized_name: "Dark Willow",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Nuker", "Disabler", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/dark_willow.png?",
        skill: "Bedlam",
        legs: 2,
    },
    {
        id: 120,
        name: "npc_dota_hero_pangolier",
        localized_name: "Pangolier",
        primary_attr: "agi",
        attack_type: "Melee",
        roles: ["Carry", "Nuker", "Disabler", "Durable", "Escape", "Initiator"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/pangolier.png?",
        skill: "Lucky Shot",
        legs: 2,
    },
    {
        id: 121,
        name: "npc_dota_hero_grimstroke",
        localized_name: "Grimstroke",
        primary_attr: "int",
        attack_type: "Ranged",
        roles: ["Support", "Nuker", "Disabler", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/grimstroke.png?",
        skill: "Stroke of Fate",
        legs: 0,
    },
    {
        id: 123,
        name: "npc_dota_hero_hoodwink",
        localized_name: "Hoodwink",
        primary_attr: "agi",
        attack_type: "Ranged",
        roles: ["Support", "Nuker", "Escape", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/hoodwink.png?",
        skill: "Sharpshooter",
        legs: 4,
    },
    {
        id: 126,
        name: "npc_dota_hero_void_spirit",
        localized_name: "Void Spirit",
        primary_attr: "int",
        attack_type: "Melee",
        roles: ["Carry", "Escape", "Nuker", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/void_spirit.png?",
        skill: "Dissimilate",
        legs: 2,
    },
    {
        id: 128,
        name: "npc_dota_hero_snapfire",
        localized_name: "Snapfire",
        primary_attr: "str",
        attack_type: "Ranged",
        roles: ["Support", "Nuker", "Disabler", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/snapfire.png?",
        skill: "Scatterblast",
        legs: 2,
    },
    {
        id: 129,
        name: "npc_dota_hero_mars",
        localized_name: "Mars",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Initiator", "Disabler", "Durable"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/mars.png?",
        skill: "Bulwark",
        legs: 2,
    },
    {
        id: 135,
        name: "npc_dota_hero_dawnbreaker",
        localized_name: "Dawnbreaker",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Carry", "Durable"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/dawnbreaker.png?",
        skill: "Luminosity",
        legs: 2,
    },
    {
        id: 136,
        name: "npc_dota_hero_marci",
        localized_name: "Marci",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Support", "Carry", "Initiator", "Disabler", "Escape"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/marci.png?",
        skill: "Dispose",
        legs: 2,
    },
    {
        id: 137,
        name: "npc_dota_hero_primal_beast",
        localized_name: "Primal Beast",
        primary_attr: "str",
        attack_type: "Melee",
        roles: ["Initiator", "Durable", "Disabler"],
        img: "https://api.opendota.com/apps/dota2/images/dota_react/heroes/primal_beast.png?",
        skill: "Onslaught",
        legs: 2,
    },
];
